### ISSUE TITLE
按照魔改的方法搭建，怎么直接报错。。。。。。

### ISSUE THREAD

**Issue by lovingfrank** [zyl6698/ss-panel-v3-mod-with-f2fpay#1]
Warning: require(/home/wwwroot/face.xxxx.com/vendor/guzzlehttp/promises/src/functions_include.php): failed to open stream: No such file or directory in /home/wwwroot/face.xxxx.com/vendor/composer/autoload_real.php on line 55

Fatal error: require(): Failed opening required '/home/wwwroot/face.xxxx.com/vendor/guzzlehttp/promises/src/functions_include.php' (include_path='.:/www/server/php/56/lib/php') in /home/wwwroot/face.xxxx.com/vendor/composer/autoload_real.php on line 55

**Comment by zyl6698** [comment]
请看最新的wiki
