### ISSUE TITLE
当点击忘记密码后得到的重置密码的链接无效

### ISSUE THREAD

**Issue by devilcn** [zyl6698/ss-panel-v3-mod-with-f2fpay#2]
您好，在部署完成后新建了用户测试重置密码，发现重置密码的链接无法正常打开。点击后如下：
404 Not Found
nginx

还请指点，感谢！

**Comment by zyl6698** [comment]
是否设置了邮箱服务？

**Comment by devilcn** [comment]
邮箱服务使用的是mailgun. 经测试可以正常收发验证码邮件及每日通知邮件。404的是点击找回密码后发来的邮件中附带的链接。还请帮助…

**Comment by zyl6698** [comment]
请开启 debug

**Comment by devilcn** [comment]
抱歉，在部署SSL后故障排除，issue closed.
