### ISSUE TITLE
mailgun提示无证书

### ISSUE THREAD

**Issue by NimaQu** [zyl6698/ss-panel-v3-mod-with-f2fpay#6]
需要手动在站点文件夹执行
`cd vendor/guzzle/guzzle/src/Guzzle/Http/Resources && wget -O cacert.pem https://curl.haxx.se/ca/cacert-2018-01-17.pem`

**Comment by zyl6698** [comment]
感谢反馈，该问题已在频道提及：[魔改版后花园](https://t.me/Modf2fc)。
